ap_lan_client_1:
    device_present: False
    platform: 'linux'
    connection: 'ssh'
    login_ip: '10.0.0.22'
    username: 'root'
    password: 'user'
    port: 22
    data_iface: 'enp3s0'
    mac: 11:22:33:44:55:66

ap_wlan_client_1:
    device_present: True
    platform: 'linux'
    connection: 'ssh'
    login_ip: '172.16.128.100'
    username: 'root'
    password: 'user'
    port: 22
    data_iface: 'wlp113s0'
    mac: aa:bb:cc:dd:ee:ff